variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1

stages:
- build
- test
- delivery

build:
    image: node:latest
    stage: build
    script:
        - cd sh-frontend
        - npm ci
        - npm run build
    artifacts:
        paths:
            - build

test:
  image: cypress/base:16.17.0
  stage: test
  script:
    - cd backend-submodule/sh-backend
    - ./gradlew build -x test
    - cd ..
    - docker-compose down --rmi all
    - docker-compose build
    - docker-compose up &
    - cd ..
    - cd sh-frontend
    - npm ci
    - npm install -g serve
    - serve -s build &
    - npm run e2e
    - docker-compose down --rmi all
  
delivery:
    stage: delivery
    script:
        - cd backend-submodule/sh-backend
        - ./gradlew build -x test
        - cd ../../
        - docker-compose build