variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 2

stages:
- prepare
- build
- test
- delivery

prepare:
    stage: prepare
    script:
        - cd sh-frontend
        - npm install
        - cd ../backend-submodule/sh-backend
        - ./gradlew build -x test
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 30 mins
        paths:
            - sh-frontend/node_modules
            - backend-submodule/sh-backend/gradle

build:
    image: node:latest
    stage: build
    script:
        - cd sh-frontend
        - $env:CI-$false
        - npm run build
    artifacts:
        paths:
            - build

test:
  image: cypress/base:16.17.0
  stage: test
  script:
    - docker compose up -d
    - cd sh-frontend
    - npm run e2e
    - docker compose down
    - docker rmi roomies/sh-backend roomies/sh-frontend
  
delivery:
    stage: delivery
    script:
        - docker compose build