variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
- build
- test
- delivery

test:
  image: node:latest
  stage: test
  script:
    - cd backend-submodule/sh-backend
    - ./gradlew build -x test
    - cd ..
    - docker-compose build
    - cd ..
    - cd sh-frontend
    - npm ci
    - npm run start:ci &
    - npm run runHeadless
  
delivery:
    stage: delivery
    script:
        - cd backend-submodule/sh-backend
        - ./gradlew build -x test
        - cd ../../
        - docker-compose build